"""init_enterprise_floor

Revision ID: 36ee394e0625
Revises: 
Create Date: 2026-05-27 22:58:47.068220

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import models  # noqa: F401  (provides models.GUID / models.JSONType)


# revision identifiers, used by Alembic.
revision: str = '36ee394e0625'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_profiles',
    sa.Column('id', models.GUID(), nullable=False),
    sa.Column('clerk_user_id', sa.Text(), nullable=False),
    sa.Column('email', sa.Text(), nullable=True),
    sa.Column('display_name', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('clerk_user_id')
    )
    op.create_table('saved_constraints',
    sa.Column('user_id', models.GUID(), nullable=False),
    sa.Column('defaults', models.JSONType(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('saved_trips',
    sa.Column('id', models.GUID(), nullable=False),
    sa.Column('user_id', models.GUID(), nullable=False),
    sa.Column('gp_slug', sa.Text(), nullable=False),
    sa.Column('depart_date', sa.Date(), nullable=True),
    sa.Column('return_date', sa.Date(), nullable=True),
    sa.Column('plan_snapshot', models.JSONType(), nullable=False),
    sa.Column('budget_summary', models.JSONType(), nullable=True),
    sa.Column('active_constraints', models.JSONType(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('saved_trips', schema=None) as batch_op:
        batch_op.create_index('ix_saved_trips_user_created', ['user_id', 'created_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('saved_trips', schema=None) as batch_op:
        batch_op.drop_index('ix_saved_trips_user_created')

    op.drop_table('saved_trips')
    op.drop_table('saved_constraints')
    op.drop_table('user_profiles')
    # ### end Alembic commands ###
